### PR TITLE
Highlight at-rules

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Added missing at-rules. Feel free to reorganize them as you wish.

### CODE REVIEW

**Comment by marijnh** [comment]
These don't seem to actually be tokens that the parser produces, so this probably doesn't do what you think it does.

**Comment by NiedziolkaMichal** [comment]
You are right, I see that separate statements would need to be created for each of those cases. Would it be possible to add `AtRule { AtKeyword commaSep<query> (";" | Block) }` to either `definitionKeyword` or `controlKeyword` so all at-rules can have the same color?

**Comment by marijnh** [comment]
What part of the rule are you trying to style?

**Comment by NiedziolkaMichal** [comment]
Its name together with '@' character. Currently it's like that:
image

@layer, @font-face, @container, @counter-style, @property & @page are marked as keywords.

**Comment by marijnh** [comment]
And they are keywords, so that seems a reasonable tag to use here?

**Comment by NiedziolkaMichal** [comment]
They are, but `from`, `to`, `selector`, `all`, `screen`, `print` are also marked as keyword. Changing color of keyword to yellow in my example, would affect more than just at-rules.

**Comment by marijnh** [comment]
Ah, I see what you mean. Does attached patch, which tags all @ keywords as `definitionKeyword`, help for you?

**Comment by NiedziolkaMichal** [comment]
That's perfect. Thank you very much.

**Comment by marijnh** [comment]
I've tagged @lezer/css 1.0.1

**Pull request closed without merging**
